-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 09:03:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbca25` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbca25` DEFAULT CHARACTER SET utf8 ;
USE `dbca25` ;

-- -----------------------------------------------------
-- Table `dbca25`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Identifiant` VARCHAR(45) NULL,
  `Mdp` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Tel` INT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`WhiteList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`WhiteList` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Tel` INT NULL,
  `Motif` VARCHAR(45) NULL,
  `Date_debut` DATETIME NULL,
  `Date_fin` DATETIME NULL,
  `Verification Admin` INT NOT NULL,
  `RFID` INT NULL,
  `Fonction` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_ Inscription user_Admin1_idx` (`Verification Admin` ASC) ,
  CONSTRAINT `fk_ Inscription user_Admin1`
    FOREIGN KEY (`Verification Admin`)
    REFERENCES `dbca25`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Acess_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Acess_log` (
  `idAcess` INT NOT NULL AUTO_INCREMENT,
  `Date_heure_entree` DATETIME NULL,
  `Resultat_tentative` VARCHAR(45) NULL,
  `Date_heure_sortie` DATETIME NULL,
  `IdUser` INT NOT NULL,
  PRIMARY KEY (`idAcess`),
  INDEX `fk_Acess_log_ Inscription user1_idx` (`IdUser` ASC) ,
  CONSTRAINT `fk_Acess_log_ Inscription user1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `dbca25`.`WhiteList` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Connect_log_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Connect_log_admin` (
  `idconnexion` INT NOT NULL AUTO_INCREMENT,
  `HeureConnexion` DATETIME NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idconnexion`),
  INDEX `fk_Connexion_Admin1_idx` (`idAdmin` ASC) ,
  CONSTRAINT `fk_Connexion_Admin1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `dbca25`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Formulaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Formulaire` (
  `idFormulaire` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Tel` INT NULL,
  `Motif` VARCHAR(45) NULL,
  `Date_debut` DATETIME NULL,
  `Date_fin` DATETIME NULL,
  `Fonction` VARCHAR(45) NULL,
  `Mail_envoye` VARCHAR(45) NULL,
  `Mail_verif` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormulaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Etat de la porte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Etat de la porte` (
  `Etat_de_la_porte` TINYINT NOT NULL,
  PRIMARY KEY (`Etat_de_la_porte`))
ENGINE = InnoDB;

USE `dbca25` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
