-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 10:23:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbca25` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbca25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbca25` DEFAULT CHARACTER SET utf8 ;
USE `dbca25` ;

-- -----------------------------------------------------
-- Table `dbca25`.`Carte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Carte` (
  `idCarte` INT NOT NULL,
  `RFDI` INT NULL,
  PRIMARY KEY (`idCarte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Tel` INT NULL,
  `Motif` VARCHAR(45) NULL,
  `Date_debut` DATETIME NULL,
  `Date_fin` DATETIME NULL,
  `Fonction` VARCHAR(45) NULL,
  `Verifier` TINYINT NULL,
  `SuperUser` TINYINT NULL,
  `Identifiant` VARCHAR(45) NULL,
  `Mdp` VARCHAR(255) NULL,
  `Mail_envoye` TINYINT NULL,
  `Mail_verif` TINYINT NULL,
  `token` VARCHAR(100) NULL,
  `Carte_idCarte` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Carte1_idx` (`Carte_idCarte` ASC) VISIBLE,
  CONSTRAINT `fk_User_Carte1`
    FOREIGN KEY (`Carte_idCarte`)
    REFERENCES `dbca25`.`Carte` (`idCarte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Acces_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Acces_log` (
  `idAcces` INT NOT NULL AUTO_INCREMENT,
  `Date_heure_entree` DATETIME NULL,
  `Resultat_tentative` VARCHAR(45) NULL,
  `Date_heure_sortie` DATETIME NULL,
  `Presence` TINYINT NULL,
  `Etat_porte` TINYINT NULL,
  `IdUser` INT NOT NULL,
  `UID` VARCHAR(50) NULL,
  PRIMARY KEY (`idAcces`),
  INDEX `fk_Acess_log_ Inscription user1_idx` (`IdUser` ASC) VISIBLE,
  CONSTRAINT `fk_Acess_log_ Inscription user1`
    FOREIGN KEY (`IdUser`)
    REFERENCES `dbca25`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbca25`.`Connect_log_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbca25`.`Connect_log_admin` (
  `idconnexion` INT NOT NULL AUTO_INCREMENT,
  `HeureConnexion` DATETIME NULL,
  `idAdmin` INT NOT NULL,
  PRIMARY KEY (`idconnexion`),
  INDEX `fk_Connect_log_admin_WhiteList1_idx` (`idAdmin` ASC) VISIBLE,
  CONSTRAINT `fk_Connect_log_admin_WhiteList1`
    FOREIGN KEY (`idAdmin`)
    REFERENCES `dbca25`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dbca25` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
